# Generated by Django 4.0.4 on 2022-05-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userstories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='created_by',
        ),
    ]
