# Generated by Django 4.0.4 on 2022-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='current_session',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
