# Generated by Django 4.0.4 on 2022-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userstory_completed_userstory_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
