# Generated by Django 4.0.4 on 2022-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mark_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='evaluated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
