# Generated by Django 4.0.4 on 2022-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userstory_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='final_mark',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
