# Generated by Django 4.0.4 on 2022-05-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userstory_description'),
        ('base', '0006_userstory_final_mark'),
    ]

    operations = [
    ]
