# Generated by Django 4.0.4 on 2022-05-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_merge_20220521_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='updated_at',
        ),
    ]
